import { UserProfile, Language, ExpenseCategory } from './types';

export const INITIAL_PROFILE: UserProfile = {
  name: '',
  age: 19,
  city: '',
  status: 'Single',
  taxRate: 12,
  salaryHistory: [],
  expenses: {
    Food: 0,
    Transport: 0,
    Entertainment: 0,
    Housing: 0,
    Shopping: 0,
    Health: 0,
    Education: 0,
    Charity: 0,
    Other: 0
  },
  currentSavings: 0,
  goals: [],
  emergencyFundMonth: 0
};

export const COLORS: Record<string, string> = {
  Food: '#10b981', 
  Transport: '#f59e0b', 
  Entertainment: '#8b5cf6', 
  Housing: '#3b82f6', 
  Shopping: '#ec4899', 
  Health: '#ef4444', 
  Education: '#0ea5e9',
  Charity: '#14b8a6',
  Other: '#64748b', 
  Savings: '#06b6d4',
  Debt: '#be123c',
  Lending: '#eab308'
};

export const EXPENSE_CATEGORIES: ExpenseCategory[] = ['Food', 'Transport', 'Entertainment', 'Housing', 'Shopping', 'Health', 'Education', 'Charity', 'Other'];
export const LOAN_TYPES = ['Bank Loan', 'Credit Card', 'Personal Loan', 'Other'];

// 50/30/20 Rule Mapping
export const BUDGET_MAPPING: Record<ExpenseCategory, 'Needs' | 'Wants' | 'Savings'> = {
  Housing: 'Needs',
  Food: 'Needs',
  Transport: 'Needs',
  Health: 'Needs',
  Education: 'Needs', // Can be savings/investment, but essential for students
  Entertainment: 'Wants',
  Shopping: 'Wants',
  Other: 'Wants',
  Charity: 'Wants', // or Spiritual Needs
};

export const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('ru-RU').format(Math.round(amount)) + ' UZS';
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  EN: {
    appTitle: "AI Financial Advisor",
    subTitle: "Halal Wealth Builder",
    incomeSettings: "Income & Salary",
    addIncome: "Add Income",
    sourcePlaceholder: "e.g. Freelance",
    loansTitle: "Loans & Liabilities",
    lendingTitle: "Assets & Lending",
    expensesTitle: "Expenses",
    addExpense: "Add Manual",
    financialHealth: "Net Worth",
    netIncome: "Net Income",
    spentThisMonth: "Spent (Month)",
    remainingBudget: "Free Cash Flow",
    monthlyBreakdown: "Monthly Breakdown",
    debtPayoff: "Debt Payoff Timeline",
    chatPlaceholder: "Ask about Islamic finance...",
    add: "Add",
    delete: "Delete",
    date: "Date",
    amount: "Amount",
    category: "Category",
    description: "Description",
    lender: "Lender",
    borrower: "Borrower",
    returnDate: "Return Date",
    totalDebt: "Total Debt",
    totalLent: "Total Lent",
    nextPay: "Recent Income",
    daysAgo: "days ago",
    today: "Today",
    healthCritical: "Critical",
    healthAttention: "Attention",
    healthFair: "Fair",
    healthGood: "Good",
    healthExcellent: "Excellent",
    noData: "No data yet",
    taxRate: "Tax Rate",
    welcome: "Welcome",
    setupProfile: "Setup Profile",
    saveProfile: "Start Journey",
    budgetPlanner: "Budget (50/30/20)",
    goals: "Savings Goals",
    netWorth: "Net Worth",
    emergencyFund: "Emergency Fund",
    inflationWarning: "Inflation Alert",
    sadaqah: "Sadaqah",
    needs: "Needs",
    wants: "Wants",
    savings: "Savings",
    remaining: "Remaining",
    createAccount: "Create Account",
    logIn: "Log In",
    signUp: "Sign Up",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot password?",
    pleaseWait: "Please wait...",
    sessionExpired: "Session expired. Please log in again.",
    logOut: "Log out",
    switchAccount: "Switch Account"
  },
  UZ: {
    appTitle: "AI Moliyaviy Maslahatchi",
    subTitle: "Halol Boylik Sari",
    incomeSettings: "Daromad",
    addIncome: "Daromad Qo'shish",
    sourcePlaceholder: "masalan: Freelance",
    loansTitle: "Qarz va Majburiyatlar",
    lendingTitle: "Aktivlar va Qarz Berish",
    expensesTitle: "Xarajatlar",
    addExpense: "Xarajat Qo'shish",
    financialHealth: "Sof Boylik",
    netIncome: "Sof Daromad",
    spentThisMonth: "Xarajat (Oy)",
    remainingBudget: "Erkin Pul Oqimi",
    monthlyBreakdown: "Taqsimot",
    debtPayoff: "Qarzni Uzish",
    chatPlaceholder: "Islomiy moliya haqida...",
    add: "Qo'shish",
    delete: "O'chirish",
    date: "Sana",
    amount: "Summa",
    category: "Toifa",
    description: "Izoh",
    lender: "Kreditor",
    borrower: "Qarz Oluvchi",
    returnDate: "Qaytish Sanasi",
    totalDebt: "Jami Qarz",
    totalLent: "Jami Berilgan",
    nextPay: "So'nggi Daromad",
    daysAgo: "kun oldin",
    today: "Bugun",
    healthCritical: "Kritik",
    healthAttention: "Diqqat",
    healthFair: "O'rtacha",
    healthGood: "Yaxshi",
    healthExcellent: "A'lo",
    noData: "Ma'lumot yo'q",
    taxRate: "Soliq",
    welcome: "Xush kelibsiz",
    setupProfile: "Profilni Sozlash",
    saveProfile: "Boshlash",
    budgetPlanner: "Byudjet (50/30/20)",
    goals: "Maqsadlar",
    netWorth: "Sof Boylik",
    emergencyFund: "Favqulodda Jamg'arma",
    inflationWarning: "Inflatsiya",
    sadaqah: "Sadaqa",
    needs: "Zarur",
    wants: "Istak",
    savings: "Jamg'arma",
    remaining: "Qolgan",
    createAccount: "Hisob yaratish",
    logIn: "Kirish",
    signUp: "Ro'yxatdan o'tish",
    username: "Foydalanuvchi nomi",
    password: "Parol",
    confirmPassword: "Parolni tasdiqlash",
    forgotPassword: "Parolni unutdingizmi?",
    pleaseWait: "Kuting...",
    sessionExpired: "Sessiya muddati tugadi. Iltimos, qayta kiring.",
    logOut: "Chiqish",
    switchAccount: "Hisobni almashtirish"
  },
  RU: {
    appTitle: "ИИ Финансовый Советник",
    subTitle: "Халяльное Богатство",
    incomeSettings: "Доходы",
    addIncome: "Добавить Доход",
    sourcePlaceholder: "напр. Фриланс",
    loansTitle: "Кредиты и Обязательства",
    lendingTitle: "Активы и Займы",
    expensesTitle: "Расходы",
    addExpense: "Добавить Расход",
    financialHealth: "Чистый Капитал",
    netIncome: "Чистый Доход",
    spentThisMonth: "Расход (Мес)",
    remainingBudget: "Свободные Деньги",
    monthlyBreakdown: "Распределение",
    debtPayoff: "Погашение Долга",
    chatPlaceholder: "Об Исламских финансах...",
    add: "Добавить",
    delete: "Удалить",
    date: "Дата",
    amount: "Сумма",
    category: "Категория",
    description: "Описание",
    lender: "Кредитор",
    borrower: "Заемщик",
    returnDate: "Дата Возврата",
    totalDebt: "Всего Долг",
    totalLent: "Всего Одолжено",
    nextPay: "Последний Доход",
    daysAgo: "дней назад",
    today: "Сегодня",
    healthCritical: "Критично",
    healthAttention: "Внимание",
    healthFair: "Нормально",
    healthGood: "Хорошо",
    healthExcellent: "Отлично",
    noData: "Нет данных",
    taxRate: "Налог",
    welcome: "Добро пожаловать",
    setupProfile: "Настройка Профиля",
    saveProfile: "Начать",
    budgetPlanner: "Бюджет (50/30/20)",
    goals: "Цели",
    netWorth: "Чистый Капитал",
    emergencyFund: "Резервный Фонд",
    inflationWarning: "Инфляция",
    sadaqah: "Садака",
    needs: "Нужды",
    wants: "Желания",
    savings: "Сбережения",
    remaining: "Остаток",
    createAccount: "Создать аккаунт",
    logIn: "Войти",
    signUp: "Регистрация",
    username: "Имя пользователя",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    forgotPassword: "Забыли пароль?",
    pleaseWait: "Пожалуйста, подождите...",
    sessionExpired: "Сессия истекла. Пожалуйста, войдите снова.",
    logOut: "Выйти",
    switchAccount: "Сменить аккаунт"
  }
};